# Generated by Django 5.1.3 on 2024-11-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_category_survey_image_survey_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('active', '進行中'), ('paused', '一時停止'), ('closed', '終了')], default='active', max_length=10, verbose_name='ステータス'),
        ),
    ]
