# Generated by Django 5.1.3 on 2024-12-04 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '004_category_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_answered', models.BooleanField(default=False, verbose_name='回答済みフラグ')),
                ('participation_date', models.DateTimeField(blank=True, null=True, verbose_name='参加日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_tracking', to='polls.survey', verbose_name='アンケート')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participated_surveys', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '回答者',
                'verbose_name_plural': '回答者一覧',
                'indexes': [models.Index(fields=['user', 'is_answered'], name='polls_surve_user_id_fb0b04_idx'), models.Index(fields=['survey', 'is_answered'], name='polls_surve_survey__6d985e_idx')],
                'unique_together': {('survey', 'user')},
            },
        ),
    ]
