# Generated by Django 5.1.3 on 2024-12-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_surveyparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyparticipant',
            name='choice_id',
            field=models.IntegerField(default=0, verbose_name='選択肢ID'),
        ),
    ]
