# Generated by Django 5.1.3 on 2024-12-15 13:15

import contest.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='theme',
            field=models.ForeignKey(default=contest.models.get_default_theme, on_delete=django.db.models.deletion.CASCADE, to='contest.theme'),
        ),
    ]
