# Generated by Django 4.2.16 on 2024-12-15 13:18

import contest.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='theme',
            field=models.ForeignKey(default=contest.models.get_default_theme, on_delete=django.db.models.deletion.CASCADE, to='contest.theme'),
        ),
    ]
